language: csharp
os: linux
dist: xenial
solution: Ribosoft.sln

mono: latest
dotnet: 3.1

sudo: false
group: travis_latest

env:
  - ASPNETCORE_ENVIRONMENT=Development DOTNET_SKIP_FIRST_TIME_EXPERIENCE=1 DOTNET_CLI_TELEMETRY_OPTOUT=1

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - deadsnakes
    - sourceline: 'deb [arch=amd64] https://packages.microsoft.com/repos/microsoft-ubuntu-xenial-prod xenial main'
      key_url: 'https://packages.microsoft.com/keys/microsoft.asc'
    packages:
    - g++-7
    - cmake
    - python3.6
    - python3-pip

services:
  - postgresql

before_install:
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-7 60 --slave /usr/bin/g++ g++ /usr/bin/g++-7

install:
  - pip3 install pipenv
  - pipenv --three && pipenv install --dev
  - ./ribosoft.py deps install --yes
  - cd Ribosoft && npm install
  - cd $TRAVIS_BUILD_DIR

before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - cp .travis/appsettings.json Ribosoft/appsettings.Development.json
  - mkdir -p RibosoftAlgo/build && cd RibosoftAlgo/build
  - cmake ..
  - cd $TRAVIS_BUILD_DIR

script:
  - cd RibosoftAlgo/build && make -j2 && bin/tests
  - cd $TRAVIS_BUILD_DIR
  - dotnet restore Ribosoft.sln && dotnet build Ribosoft.sln
  - cd Ribosoft; dotnet ef database update -c NpgsqlDbContext; cd - > /dev/null
  - dotnet test Ribosoft.Tests

deploy:
  #- provider: script
  #  script: .travis/deploy.sh "$DEVELOP_DEPLOY_URL" "$TRAVIS_BRANCH"
  #  on:
  #    branch: develop
  - provider: script
    script: .travis/deploy.sh "$MASTER_DEPLOY_URL" "$TRAVIS_BRANCH"
    on:
      branch: master
      tags: true