version: '3.8'

volumes:
  pgdata:

services:
  db:
     image: postgres:latest
     container_name: db
     restart: always
     build:
       context: .
       dockerfile: Dockerfile
     ports:
       - 5432:5432
     environment:
       POSTGRES_USER: postgres
       POSTGRES_PASSWORD: postgres
       POSTGRES_DB: ribosoft
     volumes:
       - pgdata:/var/lib/postgresql/data

  ribosoft:
    image: ${DOCKER_REGISTRY-}ribosoft
    container_name: ribosoft
    ports:
      - 5001:80
    build:
      context: .
      dockerfile: Ribosoft/Dockerfile
    depends_on:
      - "db"