name: CMake

on: [push, workflow_dispatch]

env:
  BUILD_TYPE: Release

jobs:
  build-ubuntu:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup python
      uses: actions/setup-python@v2
      with:
        python-version: 3.6
        architecture: x64

    - name: Create Build Environment
      run: cmake -E make_directory ${{runner.workspace}}/build
    
    - name: Install pip requirements
      run: pip install -r $GITHUB_WORKSPACE/requirements.txt
    
    - name: Get library dependencies
      run: python $GITHUB_WORKSPACE/ribosoft.py deps install --yes

    - name: Configure CMake
      shell: bash
      working-directory: ${{runner.workspace}}/build
      run: cmake $GITHUB_WORKSPACE/RibosoftAlgo -DCMAKE_BUILD_TYPE=$BUILD_TYPE

    - name: Build
      shell: bash
      working-directory: ${{runner.workspace}}/build
      run: cmake --build . --config $BUILD_TYPE

    - name: Test
      shell: bash
      working-directory: ${{runner.workspace}}/build
      run: ${{runner.workspace}}/build/bin/tests

  build-windows:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup python
      uses: actions/setup-python@v2
      with:
        python-version: 3.6
        architecture: x64

    - name: Create Build Environment
      run: cmake -E make_directory ${{runner.workspace}}/ribosoft/RibosoftAlgo/build
    
    - name: Install pip requirements
      run: pip install -r ./requirements.txt
    
    - name: Get library dependencies
      run: python ./ribosoft.py deps install --yes

    - name: Configure CMake
      shell: bash
      working-directory: ${{runner.workspace}}/ribosoft/RibosoftAlgo/build
      run: cmake .. -DCMAKE_BUILD_TYPE=$BUILD_TYPE

    - name: Build
      shell: bash
      working-directory: ${{runner.workspace}}/ribosoft/RibosoftAlgo/build
      run: cmake --build . --config $BUILD_TYPE

    - name: Test
      shell: cmd
      run: ${{runner.workspace}}\ribosoft\RibosoftAlgo\build\bin\Release\tests.exe
