name: RibosoftAlgo MSBuild Builds

on:
  push:
    branches: [ master, develop, tmp/update-2025 ]
  pull_request:
    branches: [ master, develop ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
        
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y g++-13 libomp-dev
        
    - name: Install Python dependencies
      run: |
        pip install pipenv
        pipenv install
        
    - name: Install C++ dependencies
      run: |
        pipenv run python ribosoft.py deps install --yes
        
    - name: Build RibosoftAlgo
      run: |
        cd RibosoftAlgo
        dotnet build --configuration Release
        
    - name: Test RibosoftAlgo
      run: |
        cd RibosoftAlgo
        # Run any C++ tests if they exist
        if [ -f "build-native.sh" ]; then
          echo "Native library built successfully"
        fi
        
    - name: Build entire solution
      run: |
        dotnet build Ribosoft.sln --configuration Release
        
    - name: Upload NuGet package
      uses: actions/upload-artifact@v4
      with:
        name: ribosoft-algo-package
        path: RibosoftAlgo/bin/Release/*.nupkg
