name: CodeCov

on: [push, workflow_dispatch]

env:
  BUILD_TYPE: Debug

jobs:
  codecov:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup python
      uses: actions/setup-python@v2
      with:
        python-version: 3.6
        architecture: x64

    - name: Setup chocolatey
      uses: crazy-max/ghaction-chocolatey@v1
      with:
        args: install opencppcoverage

    - name: Setup path
      run: set PATH=C:\Program Files\OpenCppCoverage;%PATH%

    - name: Create Build Environment
      run: cmake -E make_directory ${{runner.workspace}}/ribosoft/RibosoftAlgo/build

    - name: Install pipenv
      run: |
        pip install pipenv
        pipenv install

    - name: Get library dependencies
      run: pipenv run python ./ribosoft.py deps install --yes

    - name: Configure CMake
      shell: bash
      working-directory: ${{runner.workspace}}/ribosoft/RibosoftAlgo/build
      run: cmake .. -DCMAKE_BUILD_TYPE=$BUILD_TYPE

    - name: Build
      shell: bash
      working-directory: ${{runner.workspace}}/ribosoft/RibosoftAlgo/build
      run: cmake --build . --config $BUILD_TYPE

    - name: Generate report
      shell: bash
      working-directory: ${{runner.workspace}}/ribosoft/RibosoftAlgo
      run: OpenCppCoverage --export_type cobertura:coverage-cpp.xml --sources="${{runner.workspace}}/ribosoft/RibosoftAlgo/src" --modules="${{runner.workspace}}/ribosoft/RibosoftAlgo/build/*.dll" -- build/bin/Debug/tests.exe

    - name: Upload report
      uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        files: ./coverage-cpp.xml
        directory: ${{runner.workspace}}/ribosoft/RibosoftAlgo/