name: Deployment to FungalGenomics

on: push

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      MASTER_DEPLOY_URL: ${{ secrets.MASTER_DEPLOY_URL }}
      encrypted_201caca5971a_key: ${{secrets.ENCRYPTED_201CACA5971A_KEY}}
      encrypted_201caca5971a_iv: ${{secrets.ENCRYPTED_201CACA5971A_IV}}
    steps:
      - uses: actions/checkout@v2

      - name: Deploy application
        shell: bash
        working-directory: $GITHUB_WORKSPACE
        run: .github/deploy/deploy.sh "$MASTER_DEPLOY_URL" "${GITHUB_REF##*/}"
