name: Ribosoft .NET 8 Build and Test (Ubuntu)

on: [push, workflow_dispatch]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET 8
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'
        
    - name: Setup Python 3.13
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'
        
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y g++-13 libomp-dev
        
    - name: Install Python dependencies
      run: |
        pip install pipenv
        pipenv install
        
    - name: Install C++ dependencies
      run: |
        pipenv run python ribosoft.py deps install --yes
        
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        cache-dependency-path: './Ribosoft/npm-shrinkwrap.json'
        
    - name: Install and build frontend assets
      shell: bash
      working-directory: ./Ribosoft
      run: |
        npm ci
        npm run build:vendor
        npm run build
        
    - name: Restore .NET dependencies
      run: dotnet restore Ribosoft.sln
      
    - name: Build .NET solution
      run: dotnet build Ribosoft.sln --configuration Release --no-restore
      
    - name: Test .NET solution
      run: dotnet test Ribosoft.sln --configuration Release --no-build --verbosity normal --collect:"XPlat Code Coverage"
      
    - name: Upload coverage reports
      uses: codecov/codecov-action@v4
      with:
        files: '**/coverage.cobertura.xml'
        fail_ci_if_error: false
