name: Ribosoft .NET 8 Builds

on: [push, workflow_dispatch]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{matrix.os}}

    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET 8
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'
        
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        cache-dependency-path: './Ribosoft/npm-shrinkwrap.json'
        
    - name: Install and build frontend assets
      shell: bash
      working-directory: ./Ribosoft
      run: |
        npm ci
        npm run build:vendor
        npm run build
        
    - name: Restore .NET dependencies
      run: dotnet restore Ribosoft.sln
      
    - name: Build .NET solution
      run: dotnet build Ribosoft.sln --configuration Release --no-restore
      
    - name: Test .NET solution
      run: dotnet test Ribosoft.sln --configuration Release --no-build --verbosity normal --collect:"XPlat Code Coverage"
      
    - name: Upload coverage reports
      if: matrix.os == 'ubuntu-latest'
      uses: codecov/codecov-action@v4
      with:
        files: '**/coverage.cobertura.xml'
        fail_ci_if_error: false
