name: Robot Framework Testing

on:
  push:
    branches: [ master, develop, test-robot ]
  pull_request:
    branches: [ master, develop ]

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v2
        - run: mkdir ${{github.workspace}}/reports
        - name: Execute tests
          uses: joonvena/robotframework-docker-action@v0.1
          env:
            BROWSER: chrome
            ROBOT_TESTS_DIR: ${{github.workspace}}/test/tests
            ROBOT_REPORTS_DIR: ${{github.workspace}}/reports
        - name: Upload test results
          uses: actions/upload-artifact@v1
          if: always()
          with:
            name: reports
            path: ${{github.workspace}}/reports
    
    generate_report:
        if: always()
        needs: [test] 
        runs-on: ubuntu-latest
        steps:
        - name: Download reports
          uses: actions/download-artifact@v1
          with:
            name: reports
        - name: Send report to commit
          uses: joonvena/robotframework-reporter-action@v0.1
          env:
            GH_ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            REPO_OWNER: ${{ secrets.OWNER }}
            COMMIT_SHA: ${{ github.sha }}
            REPOSITORY: ${{ secrets.REPOSITORY_NAME }}
            REPORT_PATH: reports