name: Robot Framework Testing

on:
  push:
    branches: [ master, develop, test-robot ]
  pull_request:
    branches: [ master, develop ]

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v2
        - name: Execute tests
          uses: joonvena/robotframework-docker-action@v0.1
          env:
            BROWSER: chrome
            ROBOT_TESTS_DIR: ${{ github.workspace }}/test/tests
            ROBOT_REPORTS_DIR: ${{ github.workspace }}/test/reports
        - name: Upload test results
          uses: actions/upload-artifact@v1
          if: always()
          with:
            name: reports
            path: ${{ github.workspace }}/test/reports
    
    generate_report:
        if: always()
        needs: [test] 
        runs-on: ubuntu-latest
        steps:
        - name: Download reports
          uses: actions/download-artifact@v1
          with:
            name: reports
        - name: Get Repository Owner & Name
          run: |
            export OWNER="$(echo "${{ github.repository }}" | awk -F / '{print $1}' | sed -e "s/:refs//")"
            export REPO="$(echo "${{ github.repository }}" | awk -F / '{print $2}' | sed -e "s/:refs//")"
            echo "::set-env name=REPOSITORY_OWNER::$OWNER"
            echo "::set-env name=REPOSITORY_NAME::$REPO"
        - name: Send report to commit
          uses: joonvena/robotframework-reporter-action@v0.1
          env:
            GH_ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            REPO_OWNER: ${{ env.REPOSITORY_OWNER }}
            COMMIT_SHA: ${{ github.sha }}
            REPOSITORY: ${{ env.REPOSITORY_NAME }}
            REPORT_PATH: test/reports