name: Ribosoft2 FungalGenomics Uptime

on:
  workflow_dispatch:
    inputs:
      msg:
        description: 'Message'
  push:
    branches:
      - master
  schedule:
    - cron: '0 12 * * *'

jobs:
  uptime:
    runs-on: ubuntu-latest
    name: Ping the site
    steps:
    - name: Check the site is live
      uses: srt32/uptime@master
      with:
        url-to-hit: "https://ribosoft2.fungalgenomics.ca"
        expected-statuses: "200"
